# File and libraries

In [9]:
import pandas as pd
import numpy as np


filepath=r'data\retail_store_inventory.csv'



file_tag = "retail store inventory"

# DSLabs functions

In [10]:
%run "scripts/dslabs_functions.py"

# data functions

In [11]:
%run "scripts/data_functions.py"

data_functions loaded

# Load and sampling

In [26]:
# test_data=True
test_data=False


# Define a function to sample 10% from each group
def sample_per_day(group, fraction=0.1):
    return group.sample(frac=fraction)


if test_data==True:

    data=pd.read_csv(filepath)
    

    # data['event_timestamp'] = pd.to_datetime(data['event_timestamp'], unit='us', utc=True)
    data['Date'] = pd.to_datetime(data['Date'], infer_datetime_format=True)
 

    # Apply the sampling to each group (grouped by event_date) 1%
    # data = data.groupby('event_date').apply(lambda x: sample_per_day(x, 0.005)).reset_index(drop=True)

   

else:
    data=pd.read_csv(filepath)
    

    # data['event_timestamp'] = pd.to_datetime(data['event_timestamp'], unit='us', utc=True)
    data['Date'] = pd.to_datetime(data['Date'], infer_datetime_format=True)

    # # 10% sample
    # data = data.groupby('event_date').apply(lambda x: sample_per_day(x, 0.1)).reset_index(drop=True)
    

    

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  datetime64[ns]
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 8.4+ MB

In [27]:
data.shape

(73100, 15)

# summary 5

In [28]:
summary5 = data.describe(include="all")

summary5

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
count,73100,73100,73100,73100,73100,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100,73100.000000,73100.000000,73100
unique,NaN,5,20,5,4,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,4
top,NaN,S001,P0001,Furniture,East,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,NaN,NaN,Spring
freq,NaN,14620,3655,14699,18349,NaN,NaN,NaN,NaN,NaN,NaN,18290,NaN,NaN,18317
mean,2022-12-31 23:59:59.999999744,NaN,NaN,NaN,NaN,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,NaN,0.497305,55.146077,NaN
min,2022-01-01 00:00:00,NaN,NaN,NaN,NaN,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,NaN,0.000000,5.030000,NaN
25%,2022-07-02 00:00:00,NaN,NaN,NaN,NaN,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,NaN,0.000000,32.680000,NaN
50%,2023-01-01 00:00:00,NaN,NaN,NaN,NaN,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,NaN,0.000000,55.010000,NaN
75%,2023-07-03 00:00:00,NaN,NaN,NaN,NaN,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,NaN,1.000000,77.820000,NaN
max,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,NaN,1.000000,104.940000,NaN
std,NaN,NaN,NaN,NaN,NaN,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,NaN,0.499996,26.191408,NaN

# DataFrame Aggregation

## timeseries df creation

In [29]:
## Function for Time Series DataFrame Aggregation

# Example usage
date_col = 'Date'
groupby_cols=[]
count_cols = []
sum_cols = ['Inventory Level','Units Sold', 'Units Ordered', 'Demand Forecast']
pivot_cols = ['Region']

aggregated_df = timeseries_agg_pivot_df(data, date_col=date_col, sum_cols=sum_cols, groupby_cols=groupby_cols,pivot_cols=pivot_cols,include_totals=True)
aggregated_df

,Date,nunique_Demand Forecast_East,nunique_Demand Forecast_North,nunique_Demand Forecast_South,nunique_Demand Forecast_West,nunique_Inventory Level_East,nunique_Inventory Level_North,nunique_Inventory Level_South,nunique_Inventory Level_West,nunique_Units Ordered_East,...,nunique_Units Ordered_South,nunique_Units Ordered_West,nunique_Units Sold_East,nunique_Units Sold_North,nunique_Units Sold_South,nunique_Units Sold_West,total_Inventory Level,total_Units Sold,total_Units Ordered,total_Demand Forecast
0,2022-01-01,3057.22,3183.49,3633.08,5157.47,5432,6206,6910,9876,2304,...,2868,3420,2883,3135,3467,4999,28424,14484,10921,15031.26
1,2022-01-02,4503.95,2798.08,2359.24,4249.45,8879,5648,4576,8147,3339,...,1730,3182,4361,2680,2285,4089,27250,13415,10770,13910.72
2,2022-01-03,2500.16,3132.03,4433.18,4119.90,4624,7417,8437,6791,1751,...,3363,2969,2377,2976,4286,4042,27269,13681,11096,14185.27
3,2022-01-04,3693.04,4097.47,2482.04,4336.55,7132,7519,5125,7812,2590,...,1753,3391,3535,3963,2403,4183,27588,14084,11572,14609.10
4,2022-01-05,4112.82,3614.16,2224.51,3140.21,9129,5869,5852,7830,3142,...,2557,2822,3989,3554,2092,2937,28680,12572,10919,13091.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2023-12-28,4230.45,3338.20,4932.37,4113.83,7022,6191,7959,7622,2205,...,2800,3247,4191,3235,4887,3958,28794,16271,10077,16614.85
727,2023-12-29,3285.75,3894.18,3105.00,3641.25,5464,8087,5426,6929,2446,...,2943,2585,3109,3745,3007,3507,25906,13368,11075,13926.18
728,2023-12-30,3612.48,3322.13,3523.49,3048.56,6287,6648,7313,5535,2523,...,2946,2859,3529,3238,3405,2984,25783,13156,11224,13506.66
729,2023-12-31,3622.60,2211.44,2714.46,3073.76,8223,4636,4931,7172,2976,...,2602,2832,3522,2096,2598,2992,24962,11208,10685,11622.26
730,2024-01-01,3509.75,3902.22,1451.60,4858.93,6159,7960,4017,8340,3027,...,1962,2953,3390,3767,1370,4717,26476,13244,11234,13722.50

### drop low volume variables

In [30]:
# Calculate the rate of '0' values for each column
zero_rate = (aggregated_df == 0).mean()

# Filter columns where the rate of '0' values is higher than XX%
columns_to_drop = zero_rate[zero_rate > 0.9].index

# Drop the filtered columns
aggregated_df = aggregated_df.drop(columns=columns_to_drop)

# Display the updated DataFrame
columns_to_drop

Index([], dtype='object')

# Additional date time features

In [31]:


# # Categorize the time of day from 'date_hour' column
# def categorize_time_of_day(date_hour_str):
#     hour = int(date_hour_str.split('-')[-1])
#     if 5 <= hour < 12:
#         return 'Morning'
#     elif 12 <= hour < 17:
#         return 'Afternoon'
#     elif 17 <= hour < 22:
#         return 'Evening'
#     else:
#         return 'Night'

# aggregated_df['time_of_day'] = aggregated_df['date_hour'].apply(categorize_time_of_day)



# create year, quarter, month, day number of week, weekend/weekday based on event_date column

# Create new columns
# aggregated_df['year'] = aggregated_df['event_date'].dt.year
# aggregated_df['quarter'] = aggregated_df['event_date'].dt.quarter
# aggregated_df['month'] = aggregated_df['event_date'].dt.month
# aggregated_df['day'] = aggregated_df['event_date'].dt.day

# data['day_of_week'] = data['local_date'].dt.day_name()  

# aggregated_df['day_of_year'] = aggregated_df['event_date'].dt.dayofyear  # Day of the year
# aggregated_df['week_number'] = aggregated_df['event_date'].dt.isocalendar().week  # ISO week number

# Assuming 'local_date' is in datetime format, otherwise you can parse it using pd.to_datetime
# def week_of_month(dt):
#     first_day = dt.replace(day=1)
#     # Calculate the week of the month by comparing the current date to the first day of the month
#     return (dt.day + first_day.weekday()) // 7 + 1

# # Apply this function to your 'local_date' column
# aggregated_df['week_of_month'] = aggregated_df['event_date'].apply(week_of_month)


aggregated_df['day_of_week_nr'] = aggregated_df['Date'].dt.weekday  # Monday=0, Sunday=6
aggregated_df['is_weekend'] = aggregated_df['day_of_week_nr'].apply(lambda x: 1 if x >= 5 else 0)  # 1 for weekend, 0 for weekday


aggregated_df

,Date,nunique_Demand Forecast_East,nunique_Demand Forecast_North,nunique_Demand Forecast_South,nunique_Demand Forecast_West,nunique_Inventory Level_East,nunique_Inventory Level_North,nunique_Inventory Level_South,nunique_Inventory Level_West,nunique_Units Ordered_East,...,nunique_Units Sold_East,nunique_Units Sold_North,nunique_Units Sold_South,nunique_Units Sold_West,total_Inventory Level,total_Units Sold,total_Units Ordered,total_Demand Forecast,day_of_week_nr,is_weekend
0,2022-01-01,3057.22,3183.49,3633.08,5157.47,5432,6206,6910,9876,2304,...,2883,3135,3467,4999,28424,14484,10921,15031.26,5,1
1,2022-01-02,4503.95,2798.08,2359.24,4249.45,8879,5648,4576,8147,3339,...,4361,2680,2285,4089,27250,13415,10770,13910.72,6,1
2,2022-01-03,2500.16,3132.03,4433.18,4119.90,4624,7417,8437,6791,1751,...,2377,2976,4286,4042,27269,13681,11096,14185.27,0,0
3,2022-01-04,3693.04,4097.47,2482.04,4336.55,7132,7519,5125,7812,2590,...,3535,3963,2403,4183,27588,14084,11572,14609.10,1,0
4,2022-01-05,4112.82,3614.16,2224.51,3140.21,9129,5869,5852,7830,3142,...,3989,3554,2092,2937,28680,12572,10919,13091.70,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2023-12-28,4230.45,3338.20,4932.37,4113.83,7022,6191,7959,7622,2205,...,4191,3235,4887,3958,28794,16271,10077,16614.85,3,0
727,2023-12-29,3285.75,3894.18,3105.00,3641.25,5464,8087,5426,6929,2446,...,3109,3745,3007,3507,25906,13368,11075,13926.18,4,0
728,2023-12-30,3612.48,3322.13,3523.49,3048.56,6287,6648,7313,5535,2523,...,3529,3238,3405,2984,25783,13156,11224,13506.66,5,1
729,2023-12-31,3622.60,2211.44,2714.46,3073.76,8223,4636,4931,7172,2976,...,3522,2096,2598,2992,24962,11208,10685,11622.26,6,1
730,2024-01-01,3509.75,3902.22,1451.60,4858.93,6159,7960,4017,8340,3027,...,3390,3767,1370,4717,26476,13244,11234,13722.50,0,0

## us holidays

In [33]:
us_holidays = {
    2020: {
        'New Year\'s Day': '2020-01-01',
        'Martin Luther King Jr. Day': '2020-01-20',
        'Presidents\' Day': '2020-02-17',
        'Memorial Day': '2020-05-25',
        'Independence Day': '2020-07-04',
        'Labor Day': '2020-09-07',
        'Columbus Day': '2020-10-12',
        'Veterans Day': '2020-11-11',
        'Thanksgiving Day': '2020-11-26',
        'Christmas Day': '2020-12-25'
    },
    2021: {
        'New Year\'s Day': '2021-01-01',
        'Martin Luther King Jr. Day': '2021-01-18',
        'Presidents\' Day': '2021-02-15',
        'Memorial Day': '2021-05-31',
        'Independence Day': '2021-07-04',
        'Labor Day': '2021-09-06',
        'Columbus Day': '2021-10-11',
        'Veterans Day': '2021-11-11',
        'Thanksgiving Day': '2021-11-25',
        'Christmas Day': '2021-12-25'
    }
}

# Flatten the holidays dictionary into a single dictionary with dates as keys
holidays = {pd.to_datetime(date): name for year in us_holidays for name, date in us_holidays[year].items()}


# Create a new column 'is_holiday' that indicates whether each date is a holiday
aggregated_df['is_holiday'] = aggregated_df['Date'].apply(lambda x: 1 if x in holidays else 0)

# Display the DataFrame
aggregated_df

,Date,nunique_Demand Forecast_East,nunique_Demand Forecast_North,nunique_Demand Forecast_South,nunique_Demand Forecast_West,nunique_Inventory Level_East,nunique_Inventory Level_North,nunique_Inventory Level_South,nunique_Inventory Level_West,nunique_Units Ordered_East,...,nunique_Units Sold_North,nunique_Units Sold_South,nunique_Units Sold_West,total_Inventory Level,total_Units Sold,total_Units Ordered,total_Demand Forecast,day_of_week_nr,is_weekend,is_holiday
0,2022-01-01,3057.22,3183.49,3633.08,5157.47,5432,6206,6910,9876,2304,...,3135,3467,4999,28424,14484,10921,15031.26,5,1,0
1,2022-01-02,4503.95,2798.08,2359.24,4249.45,8879,5648,4576,8147,3339,...,2680,2285,4089,27250,13415,10770,13910.72,6,1,0
2,2022-01-03,2500.16,3132.03,4433.18,4119.90,4624,7417,8437,6791,1751,...,2976,4286,4042,27269,13681,11096,14185.27,0,0,0
3,2022-01-04,3693.04,4097.47,2482.04,4336.55,7132,7519,5125,7812,2590,...,3963,2403,4183,27588,14084,11572,14609.10,1,0,0
4,2022-01-05,4112.82,3614.16,2224.51,3140.21,9129,5869,5852,7830,3142,...,3554,2092,2937,28680,12572,10919,13091.70,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2023-12-28,4230.45,3338.20,4932.37,4113.83,7022,6191,7959,7622,2205,...,3235,4887,3958,28794,16271,10077,16614.85,3,0,0
727,2023-12-29,3285.75,3894.18,3105.00,3641.25,5464,8087,5426,6929,2446,...,3745,3007,3507,25906,13368,11075,13926.18,4,0,0
728,2023-12-30,3612.48,3322.13,3523.49,3048.56,6287,6648,7313,5535,2523,...,3238,3405,2984,25783,13156,11224,13506.66,5,1,0
729,2023-12-31,3622.60,2211.44,2714.46,3073.76,8223,4636,4931,7172,2976,...,2096,2598,2992,24962,11208,10685,11622.26,6,1,0
730,2024-01-01,3509.75,3902.22,1451.60,4858.93,6159,7960,4017,8340,3027,...,3767,1370,4717,26476,13244,11234,13722.50,0,0,0

## significant event days

In [35]:
significant_events = {
    '2020-02-02': 'Super Bowl LIV',
    '2020-03-11': 'COVID-19 Pandemic Declared',
    '2020-07-15': 'Tax Day (Extended)',
    '2020-11-03': 'US Presidential Election',
    '2020-11-26': 'Thanksgiving',
    '2020-12-25': 'Christmas',
    '2021-01-20': 'Inauguration Day',
    '2021-02-07': 'Super Bowl LV',
    '2021-04-15': 'Tax Day',
    '2021-11-25': 'Thanksgiving',
    '2021-12-25': 'Christmas'
}


commercial_events = {
    '2020-11-27': 'Black Friday',
    '2020-11-30': 'Cyber Monday',
    '2021-06-21': 'Amazon Prime Day',
    '2021-06-22': 'Amazon Prime Day',
    '2021-11-26': 'Black Friday',
    '2021-11-29': 'Cyber Monday',
}



# Flatten the significant_events dictionary into a single dictionary with dates as keys
events = {pd.to_datetime(date): name for date, name in significant_events.items()}
commercial_events = {pd.to_datetime(date): name for date, name in commercial_events.items()}

# Create a new column 'is_event' that indicates whether each date is a significant event
aggregated_df['is_major_event_day'] = aggregated_df['Date'].apply(lambda x: 1 if x in events else 0)
aggregated_df['is_commercial_event_day'] = aggregated_df['Date'].apply(lambda x: 1 if x in commercial_events else 0)

aggregated_df

,Date,nunique_Demand Forecast_East,nunique_Demand Forecast_North,nunique_Demand Forecast_South,nunique_Demand Forecast_West,nunique_Inventory Level_East,nunique_Inventory Level_North,nunique_Inventory Level_South,nunique_Inventory Level_West,nunique_Units Ordered_East,...,nunique_Units Sold_West,total_Inventory Level,total_Units Sold,total_Units Ordered,total_Demand Forecast,day_of_week_nr,is_weekend,is_holiday,is_major_event_day,is_commercial_event_day
0,2022-01-01,3057.22,3183.49,3633.08,5157.47,5432,6206,6910,9876,2304,...,4999,28424,14484,10921,15031.26,5,1,0,0,0
1,2022-01-02,4503.95,2798.08,2359.24,4249.45,8879,5648,4576,8147,3339,...,4089,27250,13415,10770,13910.72,6,1,0,0,0
2,2022-01-03,2500.16,3132.03,4433.18,4119.90,4624,7417,8437,6791,1751,...,4042,27269,13681,11096,14185.27,0,0,0,0,0
3,2022-01-04,3693.04,4097.47,2482.04,4336.55,7132,7519,5125,7812,2590,...,4183,27588,14084,11572,14609.10,1,0,0,0,0
4,2022-01-05,4112.82,3614.16,2224.51,3140.21,9129,5869,5852,7830,3142,...,2937,28680,12572,10919,13091.70,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2023-12-28,4230.45,3338.20,4932.37,4113.83,7022,6191,7959,7622,2205,...,3958,28794,16271,10077,16614.85,3,0,0,0,0
727,2023-12-29,3285.75,3894.18,3105.00,3641.25,5464,8087,5426,6929,2446,...,3507,25906,13368,11075,13926.18,4,0,0,0,0
728,2023-12-30,3612.48,3322.13,3523.49,3048.56,6287,6648,7313,5535,2523,...,2984,25783,13156,11224,13506.66,5,1,0,0,0
729,2023-12-31,3622.60,2211.44,2714.46,3073.76,8223,4636,4931,7172,2976,...,2992,24962,11208,10685,11622.26,6,1,0,0,0
730,2024-01-01,3509.75,3902.22,1451.60,4858.93,6159,7960,4017,8340,3027,...,4717,26476,13244,11234,13722.50,0,0,0,0,0

# drop irrelevant columns

In [ ]:
# aggregated_df=aggregated_df.drop(['event_date'],axis=1)

# save file

In [37]:
aggregated_df.to_csv('data/retail_store_inventory_time_pre_proc.csv',index=False)

# Excel File for encoding mapping

In [ ]:
import os
from openpyxl import load_workbook


# Function to append distinct combinations of selected columns into sheets in an Excel file
def append_columns_to_excel(df, columns_dict, output_file):
    """
    Append distinct combinations of selected columns into separate sheets in an existing Excel file,
    with the columns ordered by their names for easier hierarchical encoding and add an empty encoding column.

    Args:
    df (pd.DataFrame): The DataFrame containing the columns to save.
    columns_dict (dict): Dictionary where keys are sheet names, and values are lists of column names to include.
    output_file (str): The path of the Excel file to save the sheets.

    Returns:
    None
    """
    # Check if the file exists and is a valid Excel file
    if os.path.exists(output_file):
        try:
            # Try to load the existing workbook
            with pd.ExcelWriter(output_file, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
                writer.book = load_workbook(output_file)
                
                # Loop over each sheet name and corresponding list of columns
                for sheet_name, columns in columns_dict.items():
                    # Check if all the specified columns exist in the DataFrame
                    missing_columns = [col for col in columns if col not in df.columns]
                    if missing_columns:
                        print(f"Warning: The following columns are not found in the DataFrame for sheet '{sheet_name}': {missing_columns}")
                        continue

                    # Get distinct combinations of the selected columns
                    distinct_values = df[columns].drop_duplicates().dropna(how='all')

                    # Convert columns to strings temporarily for sorting to avoid float-string comparison errors
                    distinct_values = distinct_values.astype(str)

                    # Sort distinct values by the specified columns for hierarchical grouping
                    distinct_values.sort_values(by=columns, inplace=True)

                    # Add an empty encoding column for each column in the DataFrame
                    for col in columns:
                        distinct_values[f'{col}_enc'] = pd.NA

                    # Write distinct values to a new sheet named after the sheet_name
                    distinct_values.to_excel(writer, sheet_name=sheet_name, index=False)
                    
        except Exception as e:
            print(f"Error: {e}")
            print("The file might be corrupt or invalid. Creating a new file.")
            # Create a new file if loading fails
            with pd.ExcelWriter(output_file, engine='openpyxl', mode='w') as writer:
                for sheet_name, columns in columns_dict.items():
                    missing_columns = [col for col in columns if col not in df.columns]
                    if missing_columns:
                        print(f"Warning: The following columns are not found in the DataFrame for sheet '{sheet_name}': {missing_columns}")
                        continue

                    # Get distinct combinations of the selected columns
                    distinct_values = df[columns].drop_duplicates().dropna(how='all')

                    # Convert columns to strings temporarily for sorting
                    distinct_values = distinct_values.astype(str)

                    # Sort distinct values by the specified columns for hierarchical grouping
                    distinct_values.sort_values(by=columns, inplace=True)

                    # Add an empty encoding column for each column in the DataFrame
                    for col in columns:
                        distinct_values[f'{col}_enc'] = pd.NA

                    distinct_values.to_excel(writer, sheet_name=sheet_name, index=False)

    else:
        # If the file does not exist, create a new one
        with pd.ExcelWriter(output_file, engine='openpyxl', mode='w') as writer:
            for sheet_name, columns in columns_dict.items():
                missing_columns = [col for col in columns if col not in df.columns]
                if missing_columns:
                    print(f"Warning: The following columns are not found in the DataFrame for sheet '{sheet_name}': {missing_columns}")
                    continue

                # Get distinct combinations of the selected columns
                distinct_values = df[columns].drop_duplicates().dropna(how='all')

                # Convert columns to strings temporarily for sorting
                distinct_values = distinct_values.astype(str)

                # Sort distinct values by the specified columns for hierarchical grouping
                distinct_values.sort_values(by=columns, inplace=True)

                # Add an empty encoding column for each column in the DataFrame
                for col in columns:
                    distinct_values[f'{col}_enc'] = pd.NA

                distinct_values.to_excel(writer, sheet_name=sheet_name, index=False)
                

# Define the groups of columns for hierarchical encoding, grouped by sheet name
columns_to_save = {
    
    'device_category': ['device_category'],   
    'device_web_info_browser': ['device_web_info_browser'],   

}

# Save the distinct values combinations of each column group into corresponding sheets
# append_columns_to_excel(data_final, columns_to_save, f'data/df_merch_values_time_pre_encoding.xlsx')

# print("Excel file has been updated successfully.")